-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: trailing-whitespace
        args: ['--no-markdown-linebreak-ext']
    -   id: check-merge-conflict
    -   id: debug-statements

-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: b57843b0b874df1d16eb0bef00b868792cb245c2
    hooks:
    -   id: python-import-sorter
        args: ['--silent-overwrite']

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    sha: v1.1.0
    hooks:
    -   id: python-safety-dependencies-check

-   repo: git://github.com/chewse/pre-commit-mirrors-pydocstyle
    sha: v2.1.1
    hooks:
    -   id: pydocstyle
        args: ['--select=D300']

-   repo: git://github.com/pre-commit/mirrors-yapf
    sha: v0.20.0
    hooks:
    -   id: yapf
